export const PKG_PREFIX = '@farst'
export const PKG_NAME = 'farst'
export const PKG_CAMELCASE_NAME = 'ElementPlus'
export const PKG_CAMELCASE_LOCAL_NAME = 'ElementPlusLocale'
export const PKG_BRAND_NAME = 'Farst'
